# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bintool.ui'
#
# Created: Fri Apr 10 15:53:22 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1591, 730)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.lineEdit_bin = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_bin.setInputMask(_fromUtf8(""))
        self.lineEdit_bin.setMaxLength(32767)
        self.lineEdit_bin.setObjectName(_fromUtf8("lineEdit_bin"))
        self.verticalLayout_3.addWidget(self.lineEdit_bin)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.lineEdit_nbin = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_nbin.setObjectName(_fromUtf8("lineEdit_nbin"))
        self.verticalLayout_3.addWidget(self.lineEdit_nbin)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 0, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 0, 3, 1, 1)
        self.lineEdit_hex = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_hex.setObjectName(_fromUtf8("lineEdit_hex"))
        self.gridLayout.addWidget(self.lineEdit_hex, 1, 0, 1, 1)
        self.lineEdit_hex1 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_hex1.setObjectName(_fromUtf8("lineEdit_hex1"))
        self.gridLayout.addWidget(self.lineEdit_hex1, 1, 1, 1, 1)
        self.lineEdit_hex2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_hex2.setObjectName(_fromUtf8("lineEdit_hex2"))
        self.gridLayout.addWidget(self.lineEdit_hex2, 1, 2, 1, 1)
        self.lineEdit_hex3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_hex3.setObjectName(_fromUtf8("lineEdit_hex3"))
        self.gridLayout.addWidget(self.lineEdit_hex3, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 2, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 2, 3, 1, 1)
        self.lineEdit_nhex = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_nhex.setObjectName(_fromUtf8("lineEdit_nhex"))
        self.gridLayout.addWidget(self.lineEdit_nhex, 3, 0, 1, 1)
        self.lineEdit_nhex1 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_nhex1.setObjectName(_fromUtf8("lineEdit_nhex1"))
        self.gridLayout.addWidget(self.lineEdit_nhex1, 3, 1, 1, 1)
        self.lineEdit_nhex2 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_nhex2.setObjectName(_fromUtf8("lineEdit_nhex2"))
        self.gridLayout.addWidget(self.lineEdit_nhex2, 3, 2, 1, 1)
        self.lineEdit_nhex3 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_nhex3.setObjectName(_fromUtf8("lineEdit_nhex3"))
        self.gridLayout.addWidget(self.lineEdit_nhex3, 3, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_43 = QtGui.QLabel(self.groupBox_2)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_2.addWidget(self.label_43, 0, 3, 1, 1)
        self.lineEdit_txt = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_txt.setObjectName(_fromUtf8("lineEdit_txt"))
        self.gridLayout_2.addWidget(self.lineEdit_txt, 1, 0, 1, 1)
        self.label_42 = QtGui.QLabel(self.groupBox_2)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_2.addWidget(self.label_42, 4, 2, 1, 1)
        self.lineEdit_txt1 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_txt1.setObjectName(_fromUtf8("lineEdit_txt1"))
        self.gridLayout_2.addWidget(self.lineEdit_txt1, 1, 1, 1, 1)
        self.lineEdit_txt6 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_txt6.setObjectName(_fromUtf8("lineEdit_txt6"))
        self.gridLayout_2.addWidget(self.lineEdit_txt6, 3, 2, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_2.addWidget(self.label_33, 0, 1, 1, 1)
        self.lineEdit_txt4 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_txt4.setObjectName(_fromUtf8("lineEdit_txt4"))
        self.gridLayout_2.addWidget(self.lineEdit_txt4, 3, 0, 1, 1)
        self.label_46 = QtGui.QLabel(self.groupBox_2)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.gridLayout_2.addWidget(self.label_46, 4, 3, 1, 1)
        self.lineEdit_ntxt = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ntxt.setObjectName(_fromUtf8("lineEdit_ntxt"))
        self.gridLayout_2.addWidget(self.lineEdit_ntxt, 5, 0, 1, 1)
        self.lineEdit_ntxt1 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ntxt1.setObjectName(_fromUtf8("lineEdit_ntxt1"))
        self.gridLayout_2.addWidget(self.lineEdit_ntxt1, 5, 1, 1, 1)
        self.lineEdit_ntxt2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ntxt2.setObjectName(_fromUtf8("lineEdit_ntxt2"))
        self.gridLayout_2.addWidget(self.lineEdit_ntxt2, 5, 2, 1, 1)
        self.lineEdit_ntxt3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ntxt3.setObjectName(_fromUtf8("lineEdit_ntxt3"))
        self.gridLayout_2.addWidget(self.lineEdit_ntxt3, 5, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 6, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_2)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_2.addWidget(self.label_38, 6, 1, 1, 1)
        self.lineEdit_txt2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_txt2.setObjectName(_fromUtf8("lineEdit_txt2"))
        self.gridLayout_2.addWidget(self.lineEdit_txt2, 1, 2, 1, 1)
        self.lineEdit_txt3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_txt3.setObjectName(_fromUtf8("lineEdit_txt3"))
        self.gridLayout_2.addWidget(self.lineEdit_txt3, 1, 3, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_2)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_2.addWidget(self.label_34, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 4, 0, 1, 1)
        self.lineEdit_txt7 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_txt7.setObjectName(_fromUtf8("lineEdit_txt7"))
        self.gridLayout_2.addWidget(self.lineEdit_txt7, 3, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.label_41 = QtGui.QLabel(self.groupBox_2)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_2.addWidget(self.label_41, 4, 1, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBox_2)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_2.addWidget(self.label_35, 2, 1, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_2)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 2, 2, 1, 1)
        self.label_44 = QtGui.QLabel(self.groupBox_2)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_2.addWidget(self.label_44, 2, 3, 1, 1)
        self.lineEdit_ntxt4 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ntxt4.setObjectName(_fromUtf8("lineEdit_ntxt4"))
        self.gridLayout_2.addWidget(self.lineEdit_ntxt4, 7, 0, 1, 1)
        self.lineEdit_txt5 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_txt5.setObjectName(_fromUtf8("lineEdit_txt5"))
        self.gridLayout_2.addWidget(self.lineEdit_txt5, 3, 1, 1, 1)
        self.lineEdit_ntxt6 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ntxt6.setObjectName(_fromUtf8("lineEdit_ntxt6"))
        self.gridLayout_2.addWidget(self.lineEdit_ntxt6, 7, 2, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_2.addWidget(self.label_37, 6, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.groupBox_2)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_2.addWidget(self.label_45, 6, 3, 1, 1)
        self.lineEdit_ntxt5 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ntxt5.setObjectName(_fromUtf8("lineEdit_ntxt5"))
        self.gridLayout_2.addWidget(self.lineEdit_ntxt5, 7, 1, 1, 1)
        self.lineEdit_ntxt7 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_ntxt7.setObjectName(_fromUtf8("lineEdit_ntxt7"))
        self.gridLayout_2.addWidget(self.lineEdit_ntxt7, 7, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1591, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.toolBar_3 = QtGui.QToolBar(MainWindow)
        self.toolBar_3.setObjectName(_fromUtf8("toolBar_3"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_3)
        self.toolBar_4 = QtGui.QToolBar(MainWindow)
        self.toolBar_4.setObjectName(_fromUtf8("toolBar_4"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_4)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_bin, self.lineEdit_nbin)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BinTool v0.1 by @mhswende", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Binary", None))
        self.label.setText(_translate("MainWindow", "bin", None))
        self.label_2.setText(_translate("MainWindow", "!bin", None))
        self.groupBox.setTitle(_translate("MainWindow", "Hex", None))
        self.label_3.setText(_translate("MainWindow", "hex", None))
        self.label_7.setText(_translate("MainWindow", "hex rol 1", None))
        self.label_19.setText(_translate("MainWindow", "hex rol 2", None))
        self.label_26.setText(_translate("MainWindow", "hex rol 3", None))
        self.label_4.setText(_translate("MainWindow", "!hex", None))
        self.label_8.setText(_translate("MainWindow", "!hex rol 1", None))
        self.label_20.setText(_translate("MainWindow", "!hex rol 2", None))
        self.label_27.setText(_translate("MainWindow", "!hex rol 3", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Text", None))
        self.label_43.setText(_translate("MainWindow", "text rol 3", None))
        self.label_42.setText(_translate("MainWindow", "!text rol 2", None))
        self.label_33.setText(_translate("MainWindow", "text rol 1", None))
        self.label_46.setText(_translate("MainWindow", "!text rol 3", None))
        self.label_17.setText(_translate("MainWindow", "!text rol 4", None))
        self.label_38.setText(_translate("MainWindow", "!text rol 5", None))
        self.label_34.setText(_translate("MainWindow", "text rol 2", None))
        self.label_16.setText(_translate("MainWindow", "!text", None))
        self.label_15.setText(_translate("MainWindow", "text rol 4", None))
        self.label_41.setText(_translate("MainWindow", "!text rol 1", None))
        self.label_35.setText(_translate("MainWindow", "text rol 5", None))
        self.label_36.setText(_translate("MainWindow", "text rol 6", None))
        self.label_44.setText(_translate("MainWindow", "text rol 7", None))
        self.label_37.setText(_translate("MainWindow", "!text rol 6", None))
        self.label_45.setText(_translate("MainWindow", "!text rol 7", None))
        self.label_14.setText(_translate("MainWindow", "text", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.toolBar_3.setWindowTitle(_translate("MainWindow", "toolBar_3", None))
        self.toolBar_4.setWindowTitle(_translate("MainWindow", "toolBar_4", None))

