# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bintool.ui'
#
# Created: Thu Apr  9 20:16:17 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1275, 849)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_bin = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_bin.setInputMask(_fromUtf8(""))
        self.lineEdit_bin.setMaxLength(32767)
        self.lineEdit_bin.setObjectName(_fromUtf8("lineEdit_bin"))
        self.verticalLayout.addWidget(self.lineEdit_bin)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_nbin = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nbin.setObjectName(_fromUtf8("lineEdit_nbin"))
        self.verticalLayout.addWidget(self.lineEdit_nbin)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit_ascii2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_ascii2.setObjectName(_fromUtf8("lineEdit_ascii2"))
        self.gridLayout.addWidget(self.lineEdit_ascii2, 5, 3, 1, 1)
        self.lineEdit_ascii3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_ascii3.setObjectName(_fromUtf8("lineEdit_ascii3"))
        self.gridLayout.addWidget(self.lineEdit_ascii3, 7, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 6, 2, 1, 1)
        self.lineEdit_hex3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_hex3.setObjectName(_fromUtf8("lineEdit_hex3"))
        self.gridLayout.addWidget(self.lineEdit_hex3, 7, 2, 1, 1)
        self.lineEdit_hex = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_hex.setObjectName(_fromUtf8("lineEdit_hex"))
        self.gridLayout.addWidget(self.lineEdit_hex, 1, 2, 1, 1)
        self.lineEdit_hex1 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_hex1.setObjectName(_fromUtf8("lineEdit_hex1"))
        self.gridLayout.addWidget(self.lineEdit_hex1, 3, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 3, 1, 1)
        self.lineEdit_ascii = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_ascii.setObjectName(_fromUtf8("lineEdit_ascii"))
        self.gridLayout.addWidget(self.lineEdit_ascii, 1, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 4, 3, 1, 1)
        self.lineEdit_ascii1 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_ascii1.setObjectName(_fromUtf8("lineEdit_ascii1"))
        self.gridLayout.addWidget(self.lineEdit_ascii1, 3, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 4, 2, 1, 1)
        self.lineEdit_hex2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_hex2.setObjectName(_fromUtf8("lineEdit_hex2"))
        self.gridLayout.addWidget(self.lineEdit_hex2, 5, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 6, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_nascii = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nascii.setObjectName(_fromUtf8("lineEdit_nascii"))
        self.gridLayout_2.addWidget(self.lineEdit_nascii, 1, 3, 1, 1)
        self.lineEdit_nhex = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nhex.setObjectName(_fromUtf8("lineEdit_nhex"))
        self.gridLayout_2.addWidget(self.lineEdit_nhex, 1, 2, 1, 1)
        self.lineEdit_nascii2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nascii2.setObjectName(_fromUtf8("lineEdit_nascii2"))
        self.gridLayout_2.addWidget(self.lineEdit_nascii2, 5, 3, 1, 1)
        self.lineEdit_nascii1 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nascii1.setObjectName(_fromUtf8("lineEdit_nascii1"))
        self.gridLayout_2.addWidget(self.lineEdit_nascii1, 3, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 4, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 2, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 6, 2, 1, 1)
        self.lineEdit_nhex2 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nhex2.setObjectName(_fromUtf8("lineEdit_nhex2"))
        self.gridLayout_2.addWidget(self.lineEdit_nhex2, 5, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 6, 3, 1, 1)
        self.lineEdit_nhex3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nhex3.setObjectName(_fromUtf8("lineEdit_nhex3"))
        self.gridLayout_2.addWidget(self.lineEdit_nhex3, 7, 2, 1, 1)
        self.lineEdit_nhex1 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nhex1.setObjectName(_fromUtf8("lineEdit_nhex1"))
        self.gridLayout_2.addWidget(self.lineEdit_nhex1, 3, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 2, 2, 1, 1)
        self.lineEdit_nascii3 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_nascii3.setObjectName(_fromUtf8("lineEdit_nascii3"))
        self.gridLayout_2.addWidget(self.lineEdit_nascii3, 7, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.centralwidget)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 4, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1275, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtGui.QToolBar(MainWindow)
        self.toolBar_2.setObjectName(_fromUtf8("toolBar_2"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_bin, self.lineEdit_nbin)
        MainWindow.setTabOrder(self.lineEdit_nbin, self.lineEdit_hex)
        MainWindow.setTabOrder(self.lineEdit_hex, self.lineEdit_hex1)
        MainWindow.setTabOrder(self.lineEdit_hex1, self.lineEdit_hex2)
        MainWindow.setTabOrder(self.lineEdit_hex2, self.lineEdit_hex3)
        MainWindow.setTabOrder(self.lineEdit_hex3, self.lineEdit_ascii)
        MainWindow.setTabOrder(self.lineEdit_ascii, self.lineEdit_ascii1)
        MainWindow.setTabOrder(self.lineEdit_ascii1, self.lineEdit_ascii2)
        MainWindow.setTabOrder(self.lineEdit_ascii2, self.lineEdit_ascii3)
        MainWindow.setTabOrder(self.lineEdit_ascii3, self.lineEdit_nhex)
        MainWindow.setTabOrder(self.lineEdit_nhex, self.lineEdit_nhex1)
        MainWindow.setTabOrder(self.lineEdit_nhex1, self.lineEdit_nhex2)
        MainWindow.setTabOrder(self.lineEdit_nhex2, self.lineEdit_nhex3)
        MainWindow.setTabOrder(self.lineEdit_nhex3, self.lineEdit_nascii)
        MainWindow.setTabOrder(self.lineEdit_nascii, self.lineEdit_nascii1)
        MainWindow.setTabOrder(self.lineEdit_nascii1, self.lineEdit_nascii2)
        MainWindow.setTabOrder(self.lineEdit_nascii2, self.lineEdit_nascii3)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "BinTool v0.1 by @mhswende", None))
        self.label.setText(_translate("MainWindow", "bin", None))
        self.label_2.setText(_translate("MainWindow", "!bin", None))
        self.label_7.setText(_translate("MainWindow", "hex rol 1", None))
        self.label_10.setText(_translate("MainWindow", "hex rol 3", None))
        self.label_8.setText(_translate("MainWindow", "ascii(bin rol 1)", None))
        self.label_12.setText(_translate("MainWindow", "ascii(bin rol 2)", None))
        self.label_9.setText(_translate("MainWindow", "hex rol 2", None))
        self.label_3.setText(_translate("MainWindow", "hex", None))
        self.label_4.setText(_translate("MainWindow", "ascii", None))
        self.label_11.setText(_translate("MainWindow", "ascii(bin rol 3)", None))
        self.label_6.setText(_translate("MainWindow", "ascii", None))
        self.label_17.setText(_translate("MainWindow", "!hex rol 2", None))
        self.label_15.setText(_translate("MainWindow", "ascii(!bin rol 1)", None))
        self.label_14.setText(_translate("MainWindow", "!hex rol 3", None))
        self.label_18.setText(_translate("MainWindow", "ascii(!bin rol 3)", None))
        self.label_13.setText(_translate("MainWindow", "!hex rol 1", None))
        self.label_16.setText(_translate("MainWindow", "ascii(!bin rol 2)", None))
        self.label_5.setText(_translate("MainWindow", "!hex", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2", None))

